[project]
name = "bitcoin-address-update-value-from-excel-list"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=46.0.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "pycryptodomex>=3.23.0",
    "requests>=2.32.5",
]
